/*
    Copyright 2015
*/

#ifndef TEST_ENTRYPOINT_TEST_EPINDICATORSTEST_H_
#define TEST_ENTRYPOINT_TEST_EPINDICATORSTEST_H_

#include "gtest/gtest.h"
using namespace std;


extern "C" {
    #include "EntryPoint/epIndicators.h"
    #include "Base/err.h"
}

class TestEpIndicators : public ::testing::Test {
};

TEST_F(TestEpIndicators, reset)
{
    EpIndicators ind;
    epIndicators_reset(&ind);

    EXPECT_FALSE(IS_EPIND_STATUS_CHECK_REQ(ind));
    EXPECT_FALSE(IS_EPIND_CLESS_APP_NOT_ALLOWED(ind));
    EXPECT_FALSE(IS_EPIND_ZERO_AMOUNT(ind));
    EXPECT_FALSE(IS_EPIND_READER_CVM_REQ_LIMIT_EXCEEDED(ind));
    EXPECT_FALSE(IS_EPIND_READER_CLESS_FLOOR_LIMIT_EXCEEDED(ind));
}

TEST_F(TestEpIndicators, set)
{
    EpIndicators ind;
    epIndicators_reset(&ind);

    EXPECT_FALSE(IS_EPIND_STATUS_CHECK_REQ(ind));
    EXPECT_FALSE(IS_EPIND_CLESS_APP_NOT_ALLOWED(ind));
    EXPECT_FALSE(IS_EPIND_ZERO_AMOUNT(ind));
    EXPECT_FALSE(IS_EPIND_READER_CVM_REQ_LIMIT_EXCEEDED(ind));
    EXPECT_FALSE(IS_EPIND_READER_CLESS_FLOOR_LIMIT_EXCEEDED(ind));

    SET_EPIND_STATUS_CHECK_REQ(ind);
    EXPECT_TRUE(IS_EPIND_STATUS_CHECK_REQ(ind));

    SET_EPIND_CLESS_APP_NOT_ALLOWED(ind);
    EXPECT_TRUE(IS_EPIND_CLESS_APP_NOT_ALLOWED(ind));

    SET_EPIND_ZERO_AMOUNT(ind);
    EXPECT_TRUE(IS_EPIND_ZERO_AMOUNT(ind));

    SET_EPIND_READER_CVM_REQ_LIMIT_EXCEEDED(ind);
    EXPECT_TRUE(IS_EPIND_READER_CVM_REQ_LIMIT_EXCEEDED(ind));

    SET_EPIND_READER_CLESS_FLOOR_LIMIT_EXCEEDED(ind);
    EXPECT_TRUE(IS_EPIND_READER_CLESS_FLOOR_LIMIT_EXCEEDED(ind));


    RESET_EPIND_STATUS_CHECK_REQ(ind);
    EXPECT_FALSE(IS_EPIND_STATUS_CHECK_REQ(ind));

    RESET_EPIND_CLESS_APP_NOT_ALLOWED(ind);
    EXPECT_FALSE(IS_EPIND_CLESS_APP_NOT_ALLOWED(ind));

    RESET_EPIND_ZERO_AMOUNT(ind);
    EXPECT_FALSE(IS_EPIND_ZERO_AMOUNT(ind));

    RESET_EPIND_READER_CVM_REQ_LIMIT_EXCEEDED(ind);
    EXPECT_FALSE(IS_EPIND_READER_CVM_REQ_LIMIT_EXCEEDED(ind));

    RESET_EPIND_READER_CLESS_FLOOR_LIMIT_EXCEEDED(ind);
    EXPECT_FALSE(IS_EPIND_READER_CLESS_FLOOR_LIMIT_EXCEEDED(ind));

}

#endif// TEST_ENTRYPOINT_TEST_EPINDICATORSTEST_H_
